### ISSUE TITLE
Save data by slot to allow multi-slot operation

### ISSUE THREAD

**Issue by swh76** [slaclab/pysmurf#10]
We just started running two carriers simultaneously in the same crate and server.  We'll need to adjust the way data is saved to keep from colliding.  Maybe we can just add a directory level into /data/smurf_data/ for each slot?  e.g. data from slot 2 gets saved and retrieved from /data/smurf_data/.  pysmurf will need to know which slot it's communicating with.  Is there a better way to get that information than parsing the docker names (ie right now the dockers for slot 2 have _s2 or -s2 tagged on the end of their names).

**Comment by eyyoung24** [comment]
This is solved in Rogue 4
