### ISSUE TITLE
Data files not written if smurf2mce config parameters change

### ISSUE THREAD

**Issue by swh76** [slaclab/pysmurf#108]
See JIRA ticket https://jira.slac.stanford.edu/browse/ESCRYODET-279.  This is probably an issue with the way pysmurf interacts with smurf2mce.  Here's a simple procedure for replicating the problem:

Starting a new pysmurf session (with default num_averages=20)
```python
import time
S.stream_data_on(); time.sleep(30); S.stream_data_off()
```
produces a data file.  But if I issue this right afterward, 
```python
import time
S.stream_data_on(num_averages=10); time.sleep(30); S.stream_data_off()
```
a data file is not produced, although a mask file is.  I verified that num_averages changed from 20->10 in /data/smurf2mce_config/smurf2mce.cfg.  See the same behavior if I issue the same set of commands again.  Running the command sequence with num_averages=20 again no longer produces data, once in this state.  Rebooting pysmurf has no effect.  Rebooting the server (after running `S.stream_data_on(num_averages=10)`) and pysmurf, running `S.stream_data_on(num_averages=10);` again works.

**Comment by eyyoung24** [comment]
Closing this issue because smurf2mce is now deprecated
