### ISSUE TITLE
Save hardware configuration with data

### ISSUE THREAD

**Issue by swh76** [slaclab/pysmurf#11]
Most (all?) of the hardware knows its serial number and maybe even SLAC part number.  We should save this information with data.  The info can be retrieved using amcc_dump_bsi/etc. but Jesus had suggested using the low level IPMI commands directly, instead of those scripts.

**Comment by jesusvasquez333** [comment]
@swh76 This is a very old ticket. Now you have access to all the serial numbers and part numbers via the `atca-monitor` application. From there you can save that information. 

So, I'm closing this ticket as this seems to be resolve now.
