### ISSUE TITLE
freq_to_chan function

### ISSUE THREAD

**Issue by jlashner** [slaclab/pysmurf#125]
Is there any easy way of getting channel numbers from the `plot_tune_summary` plots? Currently we need to manually figure out how to get the channel number from the frequency that's displayed on the plots in order to disable bad channels, but it would be great if the plots also displayed channel number, or if there were a freq_to_channel function.

**Comment by eyyoung24** [comment]
The problem is when you make `plot_tune_summary`, you haven't assigned channels yet. I bet we can add something to the `freq_resp` dict after channel assignment though. Then `plot_tune_summary` could also print it.

**Comment by eyyoung24** [comment]
See the attached pull request.
