### ISSUE TITLE
Add option to suppress excessive printout from take_noise_psd

### ISSUE THREAD

**Issue by swh76** [slaclab/pysmurf#130]
Users report the long string of 

> [ 2019-10-24 21:49:47 ]  23. b0ch035: white-noise level = 315119.23 pA/rtHz, n = 1.00, f_knee = 0.00 Hz

can be annoying, and it would be nice to be able to suppress.

**Comment by eyyoung24** [comment]
see https://github.com/slaclab/pysmurf/commit/ab8d398360cb7b48f152e995ca0b565590b152e5
