### ISSUE TITLE
Fix bug printing drive_power in find_freq function

### ISSUE THREAD

**Issue by swh76** [slaclab/pysmurf#154]
https://github.com/slaclab/pysmurf/blob/8023b42a734ef1fcbf9d6a691d28931b5d09ffcd/pysmurf/tune/smurf_tune.py#L2863

**Comment by eyyoung24** [comment]
see https://github.com/slaclab/pysmurf/blob/pre-release-test-scripts/python/pysmurf/client/tune/smurf_tune.py#L2864

**Comment by swh76** [comment]
Fixed in https://github.com/slaclab/pysmurf/pull/165.
