### ISSUE TITLE
Remove seaborn dependency or make optional

### ISSUE THREAD

**Issue by swh76** [slaclab/pysmurf#158]
This dependency doesn't exist on the Pole system:

https://github.com/slaclab/pysmurf/blob/8023b42a734ef1fcbf9d6a691d28931b5d09ffcd/pysmurf/debug/smurf_noise.py#L25

we should remove it or make it optional (ie if it's not detected, pysmurf module can still load).  I think it's only used in this one function:

https://github.com/slaclab/pysmurf/blob/8023b42a734ef1fcbf9d6a691d28931b5d09ffcd/pysmurf/debug/smurf_noise.py#L1509

**Comment by slacrherbst** [comment]
you can put import calls inside functions, might help here.

**Comment by eyyoung24** [comment]
Can we just make sure it's installed in the docker? I'm happy to move if you don't like that solution.

**Comment by jesusvasquez333** [comment]
The docker image for the client already has it: 

https://github.com/slaclab/pysmurf/blob/974a1d252e6dfccebb7ab1e2d108ddca9bd62dc0/docker/client/Dockerfile#L13

But this dependency was not installed in the old Pole system, which doesn't use dockers.

**Comment by swh76** [comment]
If it's a standard library that all modern machines have by default I think that's fine, but if not I vote we move it into the function.  I'd like to keep things lightweight enough that people can use on their own laptops for analysis/etc., without having to install a bunch of unnecessary dependencies.

**Comment by swh76** [comment]
Moved the seaborn import into the function in https://github.com/slaclab/pysmurf/pull/165.
