### ISSUE TITLE
Ability to adjust config from within pysmurf

### ISSUE THREAD

**Issue by swh76** [slaclab/pysmurf#16]
Would be nice to be able to adjust your config file on the fly, like with the MCE.  For instance, measuring the Id offset for the 4K HEMT.

**Comment by cyndiayu** [comment]
This sort of already exists. See https://github.com/slaclab/pysmurf/blob/master/base/smurf_config.py which has "update" functions, and https://github.com/slaclab/pysmurf/blob/master/base/smurf_control.py#L414 to dump to file. Example of how this is done in practice is in https://github.com/slaclab/pysmurf/blob/master/tune/smurf_tune.py#L3744, which was written to be the equivalent of mce_status
