### ISSUE TITLE
lms_freq hardcoded as 4 kHz into SmurfControl initialization

### ISSUE THREAD

**Issue by mvlungu** [slaclab/pysmurf#17]
SmurfControl initialization ignores lms_freq specified in config file and loads 4kHz by default. This results in bad tracking when the real value differs significantly (e.g. 17.5 kHz for Princeton 528-box testing) and isn't explicitly specified in `tracking_setup` or `check_lock`. Problem is line 237 in `base/smurf_control.py`:
```
227:        # Dictionary for frequency response
228:        self.freq_resp = {}
229:        self.lms_freq_hz = {}
230:        self.fraction_full_scale = self.config.get('tune_band').get('fraction_full_scale')
231:        smurf_init_config = self.config.get('init')
232:        bands = smurf_init_config['bands']
233:        for b in bands:
234:            # Make band dictionaries
235:            self.freq_resp[b] = {}
236:            self.freq_resp[b]['lock_status'] = {}
237:            self.lms_freq_hz[b] = 4000
```

**Comment by swh76** [comment]
Fixed in a1c619234e6ebe48cad4df3953533ea8bda74d6a of the dspv3 branch.
