### ISSUE TITLE
Need channel numbers and band numbers in eta scan plots

### ISSUE THREAD

**Issue by swh76** [slaclab/pysmurf#22]
Let's add the channel number, band number, and tune file name (or dataset ctime, or whatever) to the eta scan plots.

![image](https://user-images.githubusercontent.com/20823858/57398040-f0bb3a80-7182-11e9-90fa-4df0fff1ae00.png)

**Comment by eyyoung24** [comment]
Closing this issue because channels and bands are not assigned when eta-scans are taken.
