### ISSUE TITLE
While taking data with pysmurf, it is difficult to quickly crossreference plots of previous runs of data taken the same day, requiring much typing of timestamps.. 

### ISSUE THREAD

**Issue by rsonka** [slaclab/pysmurf#231]
For example, if trying to look at a specific previous run of tracking, noise taking, and iv curve making from the same day, you have to eog through several different timestamps. 

Solution plan is to add an argument to allow user to append text to the plot filenames, so they can be quickly referenced with eog. It could also allow other people looking at the plots to understand more of the data taker's intent or independent variables.

**Comment by eyyoung24** [comment]
see following merge:

https://github.com/slaclab/pysmurf/pull/233
