### ISSUE TITLE
'smurf_chans' referenced before assignment bug when running take_noise_psd

### ISSUE THREAD

**Issue by swh76** [slaclab/pysmurf#249]
In master branch (and pre-release), Heather & Max report this error when running `take_noise_psd` - "local variable 'smurf_chans' referenced before assignment".  This is caused by a pysmurf indent bug here:

https://github.com/slaclab/pysmurf/blob/cf467bca4b6157c9cd7986eaa72ca1e2b925eb63/python/pysmurf/client/util/smurf_util.py#L736

I changed that block of code to 

```python
# Optionally write PyRogue configuration
            if write_config:
                config_filename=os.path.join(self.output_dir, timestamp+'.yml')
                if write_log:
                    self.log('Writing PyRogue configuration to file : '+
                         f'{config_filename}', self.LOG_USER)
                self.write_config(config_filename)

                # short wait
                time.sleep(5.)
            if write_log:
                self.log(f'Writing to file : {data_filename}',
                         self.LOG_USER)

            smurf_chans = {}
            for b in bands:
                smurf_chans[b] = self.which_on(b)
            output_mask = self.make_channel_mask(bands, smurf_chans)
            self.set_channel_mask(output_mask)
```
which I think resolves the error.  Need to create a branch with this fix to merge into master (because Princeton's still on pre-release branch, I can't merge the fix directly from there).  I'll try to do that right now.

**Comment by eyyoung24** [comment]
Fixed here: https://github.com/slaclab/pysmurf/pull/253
