### ISSUE TITLE
Get tuning based on full_band_resp working as well as find_freq/setup_notches

### ISSUE THREAD

**Issue by swh76** [slaclab/pysmurf#26]
Looks like with the newest pyrogue and firmware, full_band_resp is working again (and well!).  Can we get this *much* faster tuning method to work as reliably as the very slow find_freq/setup_notches?

**Comment by eyyoung24** [comment]
see https://github.com/slaclab/pysmurf/commit/6b143a8580179e51fc5f8f6eafc09cbf76fd8359
