### ISSUE TITLE
chan to freq map for bands >4 wrong by 2GHz

### ISSUE THREAD

**Issue by hlym** [slaclab/pysmurf#261]

**Comment by eyyoung24** [comment]
Which specific function is broken? S.channel_to_freq?

**Comment by hlym** [comment]
channel_to_freq

**Comment by jmdewart** [comment]
This is because there is a LB card in bay1.  You can fix by setting:
Base[4]:bandCenterMHz 4250
Base[5]:bandCenterMHz 4750
Base[6]:bandCenterMHz 5250
Base[7]:bandCenterMHz 5750

@eyyoung24 may want to add that as an option in the experiment config file?

**Comment by aer7** [comment]
Looks like the solution is found, closing.
