### ISSUE TITLE
ADC interleaving notch filter

### ISSUE THREAD

**Issue by jmdewart** [slaclab/pysmurf#275]
There are ADC notch filters at -134.4 and +172.8 MHz in each band.  We should exclude locking on resonators that could cross the notch.  Also issue warning if trying to set center_frequency_mhz near either of those locations.

**Comment by swh76** [comment]
Closing because this is already a pysmurf issue here:

https://github.com/slaclab/pysmurf/issues/28

but I'll paste this info there.
