### ISSUE TITLE
How do you tune on a list of resonator frequencies?

### ISSUE THREAD

**Issue by swh76** [slaclab/pysmurf#31]
The Princeton team (Shawn posting for them) asks for a minimal example for tuning on a list of known resonator frequencies (e.g. how to feed in resonator frequencies found from a VNA sweep to SMuRF for tuning).

**Comment by swh76** [comment]
This is likely not the best way, but a short term fix for mocking up the dictionary normally populated by the find_freq function from a list of resonator frequencies, called `freqs_mhz` below.  This code snippet only knows about bands 2 and 3 and you should only provide resonance frequencies in one band or the other (the script exit if you try to provide a frequencies in both bands 2 and 3 without doing anything).  You should be able to run this in place of `find_freq`.

`import os
import numpy as np

def which_band(freq):
	if freq>5e3 or freq<5.5e3:
		band=2
	if freq>5.5e3 or freq<6e3:
		band=3
	return band

freqs_mhz=[5600,5700]
bands=[which_band(f) for f in freqs_mhz]

band=None
if len(set(bands))!=1:
	print('For this simple script, all freqs must be in the same 500 MHz band')
else:
	band=bands[0]
	print('All resonance frequencies fall in band %d'%(band))
 
subbands=[]
for f in freqs_mhz:
	(subband,foff)=S.freq_to_subband(f,band)
	subbands.append(subband)	

S.freq_resp[band]['find_freq'] = {}
S.freq_resp[band]['find_freq']['subband'] = subbands
S.freq_resp[band]['find_freq']['f'] = None
S.freq_resp[band]['find_freq']['resp'] = None
timestamp=S.get_timestamp()
S.freq_resp[band]['timestamp'] = timestamp

S.freq_resp[band]['find_freq']['resonance'] = np.array(freqs_mhz) - S.get_band_center_mhz(band)

# Save 
save_name = '{}_amp_sweep_{}.txt'
np.savetxt(os.path.join(S.output_dir,save_name.format(timestamp, 'resonance')), 
           S.freq_resp[band]['find_freq']['resonance'])`

**Comment by cyndiayu** [comment]
1. We would recommend using the master channel assignment list. This has the additional benefit of being semi-self documenting. The config file points to it: https://github.com/slaclab/pysmurf/blob/master/cfg_files/experiment_fp29_smurfsrv03_noExtRef_hbOnlyBay0.cfg#L53. Edit the config file with the path to the list of new frequencies you want. I find it easiest to tune up everything, save that in a safe place, and then delete lines until you get to the subset that you want. Later, setup_notches will call that list to figure out what to actually assign. 
2. At some point once it is merged in, I wrote a more generalizable version of Shawn's script, but his should work for now until merging works.

**Comment by swh76** [comment]
Here's a much easier to use code snippet for tuning on a list of resonator frequencies that uses @cyndiayu 's nice `fake_resonance_dict` routine.

```python
tes_res=[5132.81, 5190.0, 5076.23, 5257.31, 5124.64, 5287.62, 5144.13, 5069.59, 5186.70, 5255.02, 5199.44]

S.freq_resp=S.fake_resonance_dict(tes_res)

S.setup_notches(2,new_master_assignment=True)
S.plot_tune_summary(2,eta_scan=True)
S.run_serial_gradient_descent(2)
S.run_serial_eta_scan(2)
```
