### ISSUE TITLE
Define code owners

### ISSUE THREAD

**Issue by jesusvasquez333** [slaclab/pysmurf#330]
Define code owners so that they are automatically requested for review when someone opens a pull request.  Also, code owner reviews are mandatory for merging PRs.

**Comment by slacrherbst** [comment]
As long as the code owner can be re-assigned. Responsibilities may change.

**Comment by jesusvasquez333** [comment]
Yes. They are defined in a text file, so they can be changed at any point. And being an owner only means they will be automatically assign as reviewer of some PRs, but the reviewers can also be added/removed from PRs.
