### ISSUE TITLE
Shawnhammer freezing @ UCSD

### ISSUE THREAD

**Issue by jlashner** [slaclab/pysmurf#348]
I think the problem is that the smurf_utils docker can't see the epics server:
```
cryo@smurf-srv14:~/docker/utils$ docker exec smurf_utils caget smurf_server_s2:AMCc:enable
Channel connect timed out: 'smurf_server_s2:AMCc:enable' not found.
^C
cryo@smurf-srv14:~/docker/utils$ docker exec smurf_server_s2 caget smurf_server_s2:AMCc:enable
Warning: Duplicate EPICS CA Address list entry "172.17.255.255:5064" discarded
smurf_server_s2:AMCc:enable    True
```

To make it work I'm changing the EPICS_CA_ADDR_LIST in `docker/utils/run.sh` to "localhost 172.17.255.255", but not sure if that's a permanent solution or what caused it to break in the first place.

**Comment by jesusvasquez333** [comment]
@jlashner If you update the `release-docker.sh` to the latest version [R3.4.0](https://github.com/slaclab/smurf-server-scripts/releases/tag/R3.4.0), it will have a fix for this issue. And it will generate script using the address `127.255.255.255` instead. 

We are still working on a way to communicate this fixes to you in an effective way.

**Comment by jesusvasquez333** [comment]
Using `localhost` will work as long as you need to communicate with a single server. If you need to talk to multiple servers that won't work, so it is better to use `127.255.255.255` instead, which will work with multiple servers as well.

**Comment by jlashner** [comment]
I don't know how to update the release-docker.sh and wasn't really planning on using it, since jackhammer manages dockers itself.  Is this something I need to be doing?

**Comment by jesusvasquez333** [comment]
We use `release-docker.sh` to deploy the `docker-compose.yml` and any other set of scripts (like `run.sh`) needed to run our containers. `release-docker.sh` it is not used to run/stop containers which is what jackhammer does.

In this particular case, releasing a new utils docker's set of files with the latest version of the script will solve the issue. Of course, you can also simply edit the script you are currently using as well.

**Comment by jlashner** [comment]
Right, but since jackhammer uses docker-compose to manage all of the containers I wasn't really planning on using the `run.sh` scripts

**Comment by jesusvasquez333** [comment]
I see. You don’t have to use any of those scripts, you will just need to update your docker-compose.yml, with the bug fixes we solve in the release-docker.sh scripts.

**Comment by swh76** [comment]
@jlashner Can we close this one?

**Comment by jlashner** [comment]
Yep!
