### ISSUE TITLE
Need to integrate pyrogue dependency in order to autogenerate docs for pysmurf/core

### ISSUE THREAD

**Issue by swh76** [slaclab/pysmurf#356]
I tried to add auto generation of documentation for pysmurf/core classes but am getting this error in readthedocs build:

```
WARNING: autodoc: failed to import module 'conventers.Header2Smurf' from module 'pysmurf.core'; the following exception was raised:
No module named 'pyrogue'
```

I'm not sure if there's a way to incorporate pyrogue into the readthedocs build since it's not a standard python module (or is it?).  If this is something we'd like, will need to figure that out.

**Comment by jesusvasquez333** [comment]
@swh76 Sorry, I'm not too familiar with readthedocs. Can you point me to the build logs?

**Comment by swh76** [comment]
@jesusvasquez333 will dm you on slack.  This might help:

https://stackoverflow.com/questions/16584552/how-to-state-in-requirements-txt-a-direct-github-source

**Comment by swh76** [comment]
These lines in docs/conf.py:

https://github.com/slaclab/pysmurf/blob/f6e2644612f2b05931f45cbf5ee46b4212838842/docs/conf.py#L218

instruct sphinx to ignore the rogue imports, which otherwise require building C code, which I wasn't able to find any examples of how to do easily in readthedocs.  Possibly means we're not able to link into the code in those ignored modules, but allows us to make progress on documenting the core python code without solving this issue.
