### ISSUE TITLE
Docstrings don't conform to easily parsed standards

### ISSUE THREAD

**Issue by swh76** [slaclab/pysmurf#362]
## Describe the bug

In order to automatically generate nice looking documentation from our docstrings (at least using sphinx+readthedocs) we need our docstrings to conform to either the google or numpy docstring standards (we could also write them in the lower level language but those are the two higher level standards that our autodoc environment currently supports.  Due to this we currently have over 657 errors in our autodocumentation compilation.

This is not high priority, but we should convert to one or the other of the standards (and use the standard we pick going forward).  After looking around some I like this guidance for numpy style docstrings (for more info on the options see https://bwanamarko.alwaysdata.net/napoleon/format_exception.html):

https://pandas.pydata.org/docs/development/contributing_docstring.html

(which covers additional issues I haven't seen covered elsewhere like how to mark arguments as optional or as being of different possible return types).

**Comment by swh76** [comment]
I've assigned this to me because I hate myself.  I plan to do this one small chunk of the code at a time, naming each branch something like issue362-client-base or even one file at a time with branches named things like issue362-client-base-base_class, etc.

**Comment by jesusvasquez333** [comment]
I also like the numpy style.

**Comment by swh76** [comment]
We should get our code compliant as we update our docstrings with flake8 extensions flake8-docstrings and flake8-rst-docstrings.  These can be installed like this:
```
pip3 install flake8-docstrings
pip3 install flake8-rst-docstrings
```
after which the extensions are automatically used (make sure your local flake8 is installed with pip3, not pip, so that checks are run with python3).  To see just the flake8-docstrings errors, run `flake8 --select D --docstring-convention=numpy`, while to see just the flake8-rst-docstrings errors run `flake8 --select RST --docstring-convention=numpy`.

**Comment by swh76** [comment]
Resolved with PR https://github.com/slaclab/pysmurf/pull/389.
