### ISSUE TITLE
Add 'analysis' flag to slow_iv_all

### ISSUE THREAD

**Issue by jseibert575** [slaclab/pysmurf#363]
It would help for debugging purposes, and for more general use, to add a flag about whether or not to analyze the IV data taken, before returning raw phase plots or other data products. Should be very straightforward to add, just need to check the flag to see whether or not to call the analysis code.

**Comment by aer7** [comment]
run_iv has the flag now, hopefully this satisfies.

https://github.com/slaclab/pysmurf/blob/b95a6dcb40629a0e16a16318e819960b0bf01c7b/python/pysmurf/client/debug/smurf_iv.py#L30
