### ISSUE TITLE
pysmurf should keep track of the flux ramp reset rate

### ISSUE THREAD

**Issue by swh76** [slaclab/pysmurf#37]
The flux ramp reset is an input for several functions, but not accessible from pysmurf and should be.  It should also probably be in the config.  fs in the config file should be computed using the flux ramp rate and smurf2mce config parameters instead of being redundantly specified in the config.

**Comment by eyyoung24** [comment]
Does this do what you want? https://github.com/slaclab/pysmurf/blob/2a88ba7b305af0c2ea902b8e9fdd4722fcf6bd45/command/smurf_command.py#L2561

The other important factor for some data is the downsample rate in smurf_to_mce
