### ISSUE TITLE
Include python schema package in pysmurf docker

### ISSUE THREAD

**Issue by swh76** [slaclab/pysmurf#374]
## Describe the problem
Right now, when pysmurf loads a configuration file, it validates the configuration file using the python schema package.  We don't actually import that package, right now we actually just have a copy of the code in pysmurf instead - see here: 
https://github.com/slaclab/pysmurf/blob/master/python/pysmurf/client/base/schema.py
Maintaining their code in ours is silly (and my fault).

## Describe the solution you'd like
Add the schema package to the pysmurf docker. 

## Additional details
If folks are worried about including this nonstandard dependency, there's already an option to not validate the configuration file here:

https://github.com/slaclab/pysmurf/blob/046bd8d41b9db9d133e72a0c0735a9311a1e3083/python/pysmurf/client/base/smurf_config.py#L28

we could make `validate_config=False` if the schema package isn't available for import.  I'll create a separate issue for that and assign it to me.

**Comment by jesusvasquez333** [comment]
@swh76 Why do you say the [schema](https://pypi.org/project/schema) package is nonstandard?

**Comment by swh76** [comment]
Actually, I have no idea what I mean.  If you & @eyyoung24 don't have any concerns with transitioning it to an import, I don't either.
