### ISSUE TITLE
Incorporate readthedocs into travis

### ISSUE THREAD

**Issue by swh76** [slaclab/pysmurf#382]
## Describe the problem
It'd be pretty cool if we could integrate it with travis so that PRs are forced to have no documentation errors or warnings, if that's possible.  We're not ready for this now, but I'm working to resolve all of our auto documentation errors and someday we might be able to do this.  Our documentation is currently built through readthedocs.  Low priority.

**Comment by swh76** [comment]
Two flake8 extensions that might help (these are just formatting checks, doesn't check things like whether or not all variables are properly documented) are flake8-docstrings and flake8-rst-docstrings.  However, we have thousands of errors at the moment.

**Comment by jesusvasquez333** [comment]
I added a new job in the Test stage of travis to run the documentation build command (`make html`). This way if the documentation has error that prevent it from building then the PR will be block until they are fix.

We can also make the build fail on warnings, but changing the build command to `make html SPHINXOPTS="-W --keep-going -n"`. At the moment I create a branch from the current master and the build commands runs without errors, but with 638 warnings. See the logs here:
https://travis-ci.com/github/slaclab/pysmurf/jobs/313691733

I did a local test running the build command on the `issue362-client-base-smurf_control`, and I see also 638 warnings.

So, @swh76 do you want the test to fail on warnings as well? and fix them all now? Or do you want to include test now failing only in errors, and add the "fail in warnings" feature later when all the warnings are fixed?

**Comment by swh76** [comment]
@jesusvasquez333 just merged PR https://github.com/slaclab/pysmurf/pull/389 that resolves all warnings (probably) to master.  Should be ready for adding the travis check.
