### ISSUE TITLE
Determine which bays are on from hardware, not pysmurf cfg

### ISSUE THREAD

**Issue by swh76** [slaclab/pysmurf#398]
## Describe the problem
Currently, pysmurf infers which bays have an AMC plugged in by parsing which bands are defined in the pysmurf cfg file ; see

https://github.com/slaclab/pysmurf/blob/2e37c11d3fd1afc1635b17edca93d277a33e8cdc/python/pysmurf/client/util/smurf_util.py#L3993

This is terrible.

## Describe the solution you'd like

I propose a new function `which_bays` which returns which bays are usable (e.g. have an AMC in them and are configurable) by checking

1. Which if any `--disable-bay` options were passed to the rogue startup script (this info is now accessible as described in this JIRA ticket [ESCRYODET-601](https://jira.slac.stanford.edu/browse/ESCRYODET-601)

2. Which bays have accessible PVs.  @jesusvasquez333 suggested checking if `AMCc/FpgaTopLevel/AppTop/AppCore/MicrowaveMuxCore[N]/enable` where N=bay number, 0 or 1 can be read back through epics.  See this JIRA ticket - [ESCRYODET-352](https://jira.slac.stanford.edu/browse/ESCRYODET-352).

We should also add some printout and checks to compare what the user has in their configuration file to which bays are usable.  E.g. at minimum we should report if a user is trying to configure a band that's not usable.

**Comment by jesusvasquez333** [comment]
@swh76 The options `1` and `2` are redundant. You just need to use one of those 2 approaches. I recommend using `1`

**Comment by swh76** [comment]
Thanks @jesusvasquez333 I implemented in PR#403 using approach #1.
