### ISSUE TITLE
Need human comprehensible downsampling filter/sampling rate control at runtime

### ISSUE THREAD

**Issue by swh76** [slaclab/pysmurf#4]
Need to add the ability to adjust the readout filter and the sampling rate at run time, in both internal and external timing configurations.  
  For the external timing configuration, I think that just requires adding the ability to change num_samples on the fly in smurf2mce.cfg.
  A lot of this may already exist.

**Comment by eyyoung24** [comment]
The downsampler is now implemented differently than when this request was written. But it is solved with this push: https://github.com/slaclab/pysmurf/commit/4ead641b813c3b1328fd625d36d00543d555b116

Use get/set_filter_params()
