### ISSUE TITLE
Inconsistent use of `nsamp`, `n_samp`, and `n_sample`

### ISSUE THREAD

**Issue by eyyoung24** [slaclab/pysmurf#405]
## Describe the bug
We use different conventions for the number of samples throughout the code.

## Expected behavior
Make `nsamp` consistent everywhere.

**Comment by eyyoung24** [comment]
@swh76 Yuka is taking this on. I suggested making them all `nsamp`. Do you have a preference?

**Comment by swh76** [comment]
Nope, sounds great, thanks @yukanak.

**Comment by yukanak** [comment]
Sounds good!
