### ISSUE TITLE
Error using find_freq with band 0 or 1

### ISSUE THREAD

**Issue by hlym** [slaclab/pysmurf#42]
Running find_freq with band 0 or 1 (HB card) returns the following error: 

cannot connect to smurf_server_s2:AMCc:FpgaTopLevel:AppTop:AppCore:SysgenCryo:Base[0]:digitizerFrequencyMHz

**Comment by swh76** [comment]
@hlym The fw Princeton is currently running with only supports bands 2 and 3.
