### ISSUE TITLE
Cannot connect to smurf_server_s5:AMCc:SmurfApplication:EnabledBays 

### ISSUE THREAD

**Issue by swh76** [slaclab/pysmurf#439]
## Describe the bug
Getting this error when trying to initialize a SmurfControl object in smurf rogue version 4.0.0:

```
cannot connect to smurf_server_s5:AMCc:SmurfApplication:EnabledBays 
```

I think PR https://github.com/slaclab/pysmurf/pull/428 must have broken an interface.  Probably the issue is that v4.0.0 needs to be updated since the client code that should be providing the EnabledBays register lives there?

**Comment by jesusvasquez333** [comment]
@swh76 You are correct. Changes in #428 are not backward compatible. Specifically changes to the `which_bays()` method:
https://github.com/slaclab/pysmurf/pull/428/files#diff-74e6790f626b8cc8a86107020f8671bd

which now rely on a new variable in the pysmurf server.

We can either:
- release a new version of pysmurf, which will generate a new pysmurf server docker image which will compatible with this change, 
- Make the changes in #428 backward compatible with previous versions

**Comment by jesusvasquez333** [comment]
I updated #428 to describe that an interface was changed.

**Comment by jlashner** [comment]
Didn't realize at the time this was an interface change but it makes sense. We should probably just make `which_bays` backwards compatible. Is there a fast way to check if a rogue variable exists without trying a caget?

**Comment by jesusvasquez333** [comment]
Not unfortunately the way to make it backwards compatible will be to read the new rogue variable via a caget, and if that fails then go back to read the previous variable

**Comment by jlashner** [comment]
I see, this function call should probably be cached then to avoid having a failed caget attempt for every call. I'll implement that today.

**Comment by jlashner** [comment]
Is there any chance of the bays changing within the lifetime of a single pysmurf instance? Can we assume that won't happen?

**Comment by swh76** [comment]
@jlashner safe to assume it won't happen.
