### ISSUE TITLE
Add additional constrains to the JESD health check method

### ISSUE THREAD

**Issue by jesusvasquez333** [slaclab/pysmurf#467]
## Describe the problem
We should add the following additional constrains to the Jesd health method:
```
JesdTx.DataValid (==1 per active channel)
JesdTx.StatusValidCnt (== 0 per active channel)
JesdRx.DataValid (==1 per active channel)
JesdRx.StatusValidCnt (== 0 per active channel)
JesdRx.DisparityErr (==0 per active channel)
JesdRx.NotInTableErr (==0 per active channel)
DAC.LinkErrCnt[3:0] == 0
DAC.ReadFifoEmpty[3:0] == 0
DAC.ReadFifoUnderflow[3:0] == 0
DAC.ReadFifoFull[3:0] == 0
DAC.ReadFifoOverflow[3:0] == 0
DAC.DispErr[3:0] == 0
DAC.NotitableErr[3:0] == 0
DAC.CodeSyncErr[3:0] == 0
DAC.FirstDataMatchErr[3:0] == 0
DAC.ElasticBuffOverflow[3:0] == 0
DAC.LinkConfigErr[3:0] == 0
DAC.FrameAlignErr[3:0] == 0
DAC.MultiFrameAlignErr[3:0] == 0
```

If these checks fails, subsequence data-taking operations should not be performed as they will produce incorrect data. Instead, the system should be configured again by calling the `set_defaults` command, which will trigger a call to `AppTop.Init()` to re-establish the JESD links.

**Comment by swh76** [comment]
@jesusvasquez333 what does "per active channel" here mean?  I haven't been able to connect to for instance either StatusValid or StatusValidCnt ;

> cryo@smurf-srv12:/$ cainfo smurf_server_s5:AMCc:FpgaTopLevel:AppTop:AppTopJesd[0]:StatusValidCnt
> Channel connect timed out: 'smurf_server_s5:AMCc:FpgaTopLevel:AppTop:AppTopJesd[0]:StatusValidCnt' not found.

**Comment by swh76** [comment]
One other question @ruck314 @jesusvasquez333 is there a one line description somewhere of what each of these registers means, for documentation?  I tried looking at the gui tooltips but most of them are just the register name.

**Comment by swh76** [comment]
The worry I have here is that it's going to add a lot of undecipherable functions to pysmurf.  Can we instead add a "JESD health" PV that is 1 if the above checks are ok and 0 if they're not?

**Comment by jesusvasquez333** [comment]
@swh76 I think all these check should be done in a single `JesdHelath` method, which returns `True` or `False` (or throw an ex exception that is then handle properly). Don't you have already a method to check the JESD's status?

**Comment by jesusvasquez333** [comment]
@swh76: `StatusValid` must have been a typo. It should be `DataValid`, which you have [here](https://github.com/slaclab/pysmurf/blob/728a723870eea1519afac84de5becdb473e65591/python/pysmurf/client/command/smurf_command.py#L2490-L2496) and [here](https://github.com/slaclab/pysmurf/blob/728a723870eea1519afac84de5becdb473e65591/python/pysmurf/client/command/smurf_command.py#L2452-L2458). I updated the description of this issue. 

And "per active channel" means: The register [Enable](https://github.com/slaclab/surf/blob/master/python/surf/protocols/jesd204b/_JesdTx.py#L29-L37) contains a bit mask of the enabled channels. In the screenshot you added for example that mask is `0x3cf` which means that channels 0-3, 6-9 are enabled. So the check should considered only those channels.

**Comment by jesusvasquez333** [comment]
@swh76 regarding description of these register, the only description I'm aware of is the one defined in the pyrogue files:
- [JesdRx](https://github.com/slaclab/surf/blob/master/python/surf/protocols/jesd204b/_JesdRx.py)
- [JesdTx](https://github.com/slaclab/surf/blob/master/python/surf/protocols/jesd204b/_JesdTx.py)
- [Dac38J39](https://github.com/slaclab/surf/blob/master/python/surf/devices/ti/_Dac38J84.py)

**Comment by swh76** [comment]
@jesusvasquez333 Re: the existing JESD function see;
https://github.com/slaclab/pysmurf/blob/fcf349ac9b9e2efcd153925d846174e478bde412/python/pysmurf/client/util/smurf_util.py#L2043
that just checks that the JESD enable is equal to valid.  We can add these more comprehensive checks to pysmurf but I'll need at least a one line description of what each of these registers are so I can document them in the API, since it'll be adding a lot of new register gets and sets to pysmurf.

**Comment by jesusvasquez333** [comment]
@swh76 Why don't you expand `check_jesd` to do all those additional checks?

**Comment by swh76** [comment]
Started a discussion on this on slack.  We can, but pysmurf is the user interface so we need to document everything (not that everything's documented now, but trying to not add anything new without documentation since otherwise we'll never get the documentation under control).  If we want these checks in pysmurf, will need descriptions of each of the registers.

**Comment by jesusvasquez333** [comment]
We are going to implement this function in the server side, as a Rogue Command that will then be called from the pysmurf client. This function should return `True` if all checks pass or `False` otherwise.

**Comment by swh76** [comment]
Awesome, thanks.

**Comment by jesusvasquez333** [comment]
@swh76 I generated a release of `cryo-det` which includes a new ZIP file: [MicrowaveMuxBpEthGen2_v0.3.0](https://github.com/slaclab/cryo-det/releases/tag/MicrowaveMuxBpEthGen2_v0.3.0). The new ZIP file includes the new `JesdHealth` method to check the status of the JESD links. 

I'm working on branch [issue467](https://github.com/slaclab/pysmurf/tree/issue467), where I included some wrappers registers to call and read the status from that method. I added these 2 new register under `SmurfApplication`:
- `CheckJesd`: it is a command used to trigger a call to the new `AppTop.JesdHealth` method. The command will check if the ZIP file's `AppTop` device contains the new `JesdHealth` method. 
- `JesdStatus`: this will container the status of the `CheckJesd`. It is a `enum` register with these states 
  - `Unlocked`: The `AppTop.JesdHealth` said the JESD were not locked,
  - `Locked`: The `AppTop.JesdHealth` said the JESD were locked,
  - `Checking`: The `AppTop.JesdHealth` command is in progress, and 
  - `Not found`: The ZIP file does not contains the `AppTop.JesdHealth`  method.

@swh76 can you work on this branch [issue467](https://github.com/slaclab/pysmurf/tree/issue467) and add the client side code? I tested with this code:
```python
def check_jesd():
    """
    Check JESD Health.

    This method returns True is the JesdHealth command returns True,
    which means the JESD are locked.
    """

    # Optional, measure how long the process take
    start_time = time.time()

    # First, check if the 'JesdStatus' register is set to 'Not found'. That means that the 
    # current ZIP file does not contain the new JesdHealth command.
    status = epics.caget(f'{epics_prefix}:AMCc:SmurfApplication:JesdStatus', as_string=True)

    if status == "Not found":
        print("Command not implemented") # This should go to the logs instead.
        return False  # Or maybe handle this error in a different way?

    # If the command exist, then start by calling the 'CheckJesd' wrapper command.
    epics.caput(f'{epics_prefix}:AMCc:SmurfApplication:CheckJesd', 1, wait=True)

    # Now let's wait for it to finish. We define a maximum
    # time we will wait, 60 seconds in this case, divided in smaller 
    # tries of 5 second each
    max_timeout=60
    caget_timeout=5
    num_retries=int(max_timeout/caget_timeout)
    success=False
    for i in range(num_retries):
        # Try to read the status register
        ret = epics.caget(f'{epics_prefix}:AMCc:SmurfApplication:JesdStatus', as_string=True, timeout=caget_timeout)

        # If we can not read the PV, or if the PV returns 'Checking', 
        # then we keep trying.
        if ret not in [None, 'Checking']:
            success=True
            break

    # If after out maximum defined timeout, we weren't able to read the 
    # "JesdStatus" status register with a valid state, then we exit on error.
    if not success:
        print('ERROR. The JESD check did not finished after {max_timeout} seconds.') # This should go to the logs instead.
        return False

    # Optional, measure how long the process take
    end_time = time.time()
    print(f'JESD check finished after {int(end_time - start_time)} seconds. The final state was {ret}') # Optional and should go to the logs instead.

    # Return True if the PV returned 'Locked'. Otherwise return False
    if ret == "Locked":
        return True
    else:
        return False
```
