### ISSUE TITLE
Description of header word 6 is misleading

### ISSUE THREAD

**Issue by mhasself** [slaclab/pysmurf#505]
README.SmurfPacket.md describes word 6 as "64 bit unix time" / "64 bit unix time nanoseconds".  I have been told by @joseffrisch that "word 6 is in standard 64 bit unix time in nanoseconds from 1970 from server. This is locked to NTP/PTP in the server so on long time scales should be correct."

But the [implementation](https://github.com/slaclab/pysmurf/blob/184271182de63976de401f7562085c9bbf9b5520/include/smurf/core/common/Helpers.h#L73-L74) uses [steady_clock](https://en.cppreference.com/w/cpp/chrono/steady_clock), which is not connected to wall clock time at all.  Rather, it is guaranteed monotonic, which is of course very useful for other reasons.

From an SO perspective, changing the docs is an acceptable solution... we will add a system timestamp in our streaming processor.

**Comment by jesusvasquez333** [comment]
I transferred this issue to pysmurf so that it has visibility to the rest of the team.

**Comment by jesusvasquez333** [comment]
@joseffrisch @mhasself Yes, we can change the current implementation of this time word in the header if needed.

At the moment we use `steady_clock` which is a monolithic clock. We can change to any other type of clock, like for example `system_clock` which represent the wall clock but is, however, non-monolithic.

**Comment by joseffrisch** [comment]
I think either could be OK but I think I would suggest using system_clock because a failure mode where somehow SMuRF time got unlocked from real world time would otherwise be difficult to detect.

There isn’t a likely mechanism for out-of-order frames that would not be detected with the frame counters.

It’s completely up to SO which they prefer.

**Comment by mhasself** [comment]
> At the moment we use `steady_clock` which is a monolithic clock. We can change to any other type of clock, like for example `system_clock` which represent the wall clock but is, however, non-monolithic.

Sorry for not following up on this, I thought I had.  Perhaps I mentioned it on a call.  In any case:

We would really like this word to be changed to report a `system_clock`, if that's still acceptable.  A real timestamp is needed for some kinds of lab tests, in cases where we don't have the full timing system.

**Comment by joseffrisch** [comment]
Just making sure Matt Weaver is on the list.  Matt, how much work is it to change this?

**Comment by jesusvasquez333** [comment]
@mhasself Not problem, I will change it to `system_clock`. I will try too squeeze this change in the next release.
