### ISSUE TITLE
Add a flag to skip IV analysis when running S.run_iv

### ISSUE THREAD

**Issue by jseibert575** [slaclab/pysmurf#512]
Assigning to myself, adding a flag to skip the built-in analysis when running IV curves and just output the raw data.

**Comment by eyyoung24** [comment]
This is great.

I think you can add `analyze=True` to the declaration of the function. Then just add `if analyze:` before this line
https://github.com/slaclab/pysmurf/blob/184271182de63976de401f7562085c9bbf9b5520/python/pysmurf/client/debug/smurf_iv.py#L161

**Comment by eyyoung24** [comment]
And also make it output a warning message to log if `analyze=False`.
