### ISSUE TITLE
Remove divide by 4.

### ISSUE THREAD

**Issue by msilvafe** [slaclab/pysmurf#525]
https://github.com/slaclab/pysmurf/blob/184271182de63976de401f7562085c9bbf9b5520/scratch/shawn/measureFluxRampFvsV.py#L171

The divide by 4 needs to be removed here in order to get the scaling right for taking DC SQUID curves using get_loop_filter_output_array.

**Comment by aer7** [comment]
This change is in the main branch. Thanks!

https://github.com/slaclab/pysmurf/blob/b5b8c054da2ee365128a25571cea64475c1f1b09/scratch/shawn/measureFluxRampFvsV.py#L171
