### ISSUE TITLE
Integrate SO publisher into pysmurf dspv3 branch

### ISSUE THREAD

**Issue by swh76** [slaclab/pysmurf#54]
We pushed the SO publisher into the master branch, but no one is using that branch.  Need to push into the dspv3 branch so it can be distributed into the test institution branches (nist-cmb, nist-xray, and pton-dspv3).

**Comment by eyyoung24** [comment]
This is already part of the main branch, see: https://github.com/slaclab/pysmurf/pull/19

Should just merge dspv3 into main.

**Comment by swh76** [comment]
We should merge dspv3 into master, but for now I've cherry picked the publisher from the master branch into the dspv3 branch - see https://github.com/slaclab/pysmurf/commit/c327180e1debe16ed2dd2e92e2d7380abae91c27.
