### ISSUE TITLE
Streamed TES bias data does not include arbitrary waveform data

### ISSUE THREAD

**Issue by jlashner** [slaclab/pysmurf#559]
## Describe the bug
The TES bias data streamed from the pysmurf server does not capture any of the bias voltages generated in firmware. For example, if we set the bias with `S.set_tes_bias_bipolar`, this bias value will show up in the data stream, however if we play a waveform with `S.play_sine_tes`, this bias data will not show up in the data stream.

## To Reproduce
Run `S.play_sine_tes` and look at the streamed bias data. It is not a sine wave.

## Expected behavior
It should be a sine wave.

## Additional details
This is very important for some detector characterization measurements such as complex impedance, and it's kind of concerning that the bias data we are receiving in the data stream may not actually represent the true biases being set.

**Comment by swh76** [comment]
I am not sure but I think this was known and has been solved since our release.  Mitch & Ed I think implemented the fix and can say more.

**Comment by jmdewart** [comment]
The software server is currently overwriting firmware streamed TES header information (wasn't previously available).  Firmware now streams the TES bias and the software TES bias feature will be removed in the next release.

**Comment by jlashner** [comment]
Awesome, thanks! Do you have a rough estimate when this will be released?

**Comment by jesusvasquez333** [comment]
We have an internal JIRA ticket for this issue, to remove the SW section which writes the TES to the header: https://jira.slac.stanford.edu/browse/ESCRYODET-763
