### ISSUE TITLE
Smurf Server Publisher modifications

### ISSUE THREAD

**Issue by jlashner** [slaclab/pysmurf#588]
## Describe the problem
I'm finally getting around to testing out the "publish" Variable Group for smurf metadata, and it seems to work well, though there are a few enhancements that may be necessary.

1. The msgtype [here](https://github.com/slaclab/pysmurf/blob/d61883006f306d431b036e99baa1f44413259df9/python/pysmurf/core/utilities/_SmurfPublisher.py#L198-L199) should be something other then `general` so we can easily distinguish metadata messages from other message types (for instance log_start). I suggest changing it to `metadata`.
2. It would be great if we could retain type information in the message instead of converting all queries to string. I believe the message data can be anything as long as its json serializable, so we should take advantage of that. I think this includes most types contained in rogue registers, though numpy need to be converted to lists first.

## Describe the solution you'd like
1. I think the message type should be changed to `metadata`
2. Instead of publishing a string, I think we should publish the key, val pair as a tuple, retaining the register type.

**Comment by jesusvasquez333** [comment]
Hi @jlashner, 

Changing the message type to `metadata` sounds good to me. That shouldn't be a problem.

For the published data, we can do something like this: in the [SmurfPublisher _varListen method](https://github.com/slaclab/pysmurf/blob/main/python/pysmurf/core/utilities/_SmurfPublisher.py#L198-L199), we can return this message data instead:
```python
data=json.dumps({"path": path, "value": varVal.value, "type": varVal.typeStr})
```

That includes the register's `path`, `type`, and `value` in a JSON format. 

How does that sound?

**Comment by jlashner** [comment]
That would work, but there's no reason `data` has to be a string if `varVal.value` is already JSON serializable, since the whole published data packet is being dumped to JSON [here](https://github.com/slaclab/pysmurf/blob/3a502b6ad6d8cd6605ececad99d3965901bd8cf9/python/pysmurf/core/utilities/_SmurfPublisher.py#L152).

If `varVal.value` is already serializable I think we should just do something like:
```
data={"path": path, "value": varVal.value, "type": varVal.typeStr}.
```
If I remember correctly though, values can be a `np.ndarray` in which case we'd need to call `varVal.value.tolist()` before passing.
