### ISSUE TITLE
Catch caget timeouts

### ISSUE THREAD

**Issue by eyyoung24** [slaclab/pysmurf#589]
## Describe the bug
caget occasionally times out. It returns None, which breaks future functions.

## Additional details
Add any other details about the problem here.

**Comment by jesusvasquez333** [comment]
Just to complete the issue description: according to the `pyepics` documentation, a `get` command returns `None` indicates a incomplete get: https://github.com/pyepics/pyepics/blob/master/epics/ca.py#L1423
