### ISSUE TITLE
find_freq missing first resonator

### ISSUE THREAD

**Issue by swh76** [slaclab/pysmurf#60]
For some reason the find_freq function in dspv3 systematically misses the first resonance (where by first I mean the lowest frequency one).  It clearly is finding the resonance (because it's highlighted with a gray bar) but still doesn't identify it somehow.  See e.g.:

![image](https://user-images.githubusercontent.com/20823858/61163422-b93e7680-a4c2-11e9-8654-78856ce2831d.png)

I've confirmed that if I change the number of subbands I sweep, the left most resonator always get missed.

**Comment by swh76** [comment]
PS I'm like 90% sure this problem started after I made this commit:

https://github.com/slaclab/pysmurf/commit/d6351acb1c48b9f963fb23248cd1490210d9e96e

**Comment by eyyoung24** [comment]
Fixed here: https://github.com/slaclab/pysmurf/commit/9e83b6156bb71b61dac46d7693c69d156f43c6e6
