### ISSUE TITLE
analyze_iv_from_file writes to path that may not exist in offline mode

### ISSUE THREAD

**Issue by dpdutcher** [slaclab/pysmurf#605]
## Describe the bug
analyze_iv_from_file automatically saves results to the output directory loaded from the input numpy directory. If running in offline mode (and using the `datafile` kwarg), this directory may not exist.

## To Reproduce
1. Run IV script
2. Transfer outputs to a machine without the /data/smurf_data directory structure
3. Use analyze_iv_from_file to analyze the IV outputs.

## Expected behavior
Either the data is saved to a path scraped from the `datafile` kwarg, the save path is allowed to be specified in the function call, or the results are returned to be used interactively.

**Comment by kmharrington** [comment]
I've written a fix for this. What's the process for getting a branch here and making a PR? I'm seeing that I don't have permission to add/PR a branch right now.
