### ISSUE TITLE
Functions like take_noise_psd should run on all channels, not just one band at a time

### ISSUE THREAD

**Issue by swh76** [slaclab/pysmurf#61]
At the Berkeley SO 2019 F2F, users request that functions like take_noise_psd https://github.com/slaclab/pysmurf/blob/be01b4e61abfda5e4ef77f60a8bfe6a05d2f56b2/debug/smurf_noise.py#L11 run over all channels, not just one band at a time.  Currently, pysmurf already streams all active channels (up to 512) to the data file regardless of band, so the data is already accessible.

**Comment by eyyoung24** [comment]
This was duplicated but also solved: https://github.com/slaclab/pysmurf/commit/ab8d398360cb7b48f152e995ca0b565590b152e5
