### ISSUE TITLE
Efficiency of .dat files

### ISSUE THREAD

**Issue by jlashner** [slaclab/pysmurf#626]
## Describe the bug
For some reason .dat files that are written on SO systems are very space inefficient. For example: Max streamed 4 channels over the weekend, which created a  320GB .dat file, while the g3 data was just 16 GB. This is an ongoing problem at pretty much all test institutions which causes disk space to quickly fill up unreasonably fast.

Matthew also created a script that analyzes the contents of the files, which outputs the following for a standard file: 

```
Reading /mnt/so1/users/jlashner/dat_files/uchicago_missing_data.dat...
  On frame 1, payload size 8320

Analysis:

  Number of frames by "channel":
    ChannelId.Processed           :    238757
    ChannelId.Metadata            :      1193

  Spatial analysis:
    metadata    :    186108     0.0%
    header      :  30560896     1.5%
    stream_data :  93592744     4.7%
    padding     : 1862304600    93.7%

  Summary of FrameCounter steps:
        20 :     238722  99.99%
        26 :          1   0.00%
        25 :          5   0.00%
        29 :          4   0.00%
        27 :          2   0.00%
        24 :          6   0.00%
        31 :          2   0.00%
        30 :          2   0.00%
        32 :          1   0.00%
        23 :          3   0.00%
        33 :          2   0.00%
        35 :          1   0.00%
        22 :          2   0.00%
        37 :          1   0.00%
        38 :          1   0.00%
        21 :          1   0.00%
    other  :          0   0.00%

  Data frame count is    238757 frames in 1193.852 seconds
  Internal frequency     3999.967 Hz
  Readout frequency      199.998 Hz
  Channel counts encountered: {98}
```

Note that 93% of the file is padding. Comparing G3 files with .dat files, it seems like when taking data with `stream_data_on` and `take_stream_data`, the PayloadSize is not being set to match the channel count, so each frame is large enough to hold 4096 channels even though there are only a few real data channels. I think this should be a pretty easy fix to the stream-data functions to just add a line setting the PayloadSize correctly.

**Comment by jesusvasquez333** [comment]
Note that you can set the `PayloadSize ` register under the `ChannelMapper` to `0` in order to make the output frame to contain only the number of channels defined in the `Mask` list (i.e. no padding), as described here:
https://github.com/slaclab/pysmurf/blob/main/README.SmurfProcessor.md#channelmapper

**Comment by jlashner** [comment]
That's easy, is there any reason we'd wouldn't want to just keep the payload size at 0?

**Comment by jesusvasquez333** [comment]
I don't see any reason for not keeping the payload size set to 0, but @eyyoung24 should comment on why this is not the case currently. Maybe there is a reason I'm not aware of.
