### ISSUE TITLE
Add hooks for StreamDataSource

### ISSUE THREAD

**Issue by jlashner** [slaclab/pysmurf#637]
## Describe the problem
The StreamDataSource is very useful when running tests in emulation mode, and it would be nice to have command hooks for `StreamDataSource:SourceEnable` and `StreamDataSource:Period`

**Comment by aer7** [comment]
I think the gets and sets for SourceEnable and Period are present. Does this do what you're looking for?

https://github.com/slaclab/pysmurf/blob/41e41c9c568aecd7e350ff2f050be58498c56af9/python/pysmurf/client/command/smurf_command.py#L6028

**Comment by jlashner** [comment]
yep, that should do it, thanks!
