### ISSUE TITLE
Make --bias-group flag in smurf_cmd.py more useful

### ISSUE THREAD

**Issue by ramiro050** [slaclab/pysmurf#659]
## Describe the problem
Currently the `smurf_cmd.py` script allows setting the tes bias of a single
bias group by using the `--bias-group` flag. However, it would be nice to be
able to set the bias for multiple groups in a single command instead of calling
`smurf_cmd.py` over and over.

## Describe the solution you'd like
The default behavior of the `bias-group` should be left unchanged. However,
if the user passes an array of groups (example: `--bias-group '1 3 5'`), `smurf_cmd.py` 
should loop over the array of groups and set the bias for each.

**Comment by swh76** [comment]
@ramiro050 we're not planning to fix this but you're welcome to issue a PR with a fix.
