### ISSUE TITLE
All RTM slow DACs rail full scale negative during setDefaults

### ISSUE THREAD

**Issue by Prakamya01** [slaclab/pysmurf#753]
## Describe the bug
During setup, the hemt1 gate voltage sometimes goes full scale negative. 

## To Reproduce
1. Connect hemt1 to a multimeter and oscilloscope 
2. run shawnhammer (i.e. shawnhammer -c /data/smurf_startup_cfg/smurf_startup_timingtests.cfg); keep an eye on the oscilloscope and multimeter
3. see error

## Expected behavior
Running shawnhammer runs set_amp_defaults() which sets hemt1 to 0.265V, so hammering at any time should reflect this

**Comment by dpdutcher** [comment]
Is this what is causing my UFM temperatures to shoot up by more than 100mK upon hammering?
Because that's a major issue.

**Comment by swh76** [comment]
Ready to PR (https://github.com/slaclab/pysmurf/pull/763) but unable to release due to https://github.com/slaclab/pysmurf/issues/764.
