### ISSUE TITLE
setup_notches should check if there are any resonances first

### ISSUE THREAD

**Issue by eyyoung24** [slaclab/pysmurf#76]

**Comment by swh76** [comment]
Got hit by this again at NIST.  Currently, `setup_notches` crashes if no resonances were found by `find_freq` here:
https://github.com/slaclab/pysmurf/blob/5a6a4c6ba09db90ab5caddb534a1ee43f17beeff/pysmurf/tune/smurf_tune.py#L1500
and it's confusing.  Compounded by issue https://github.com/slaclab/pysmurf/issues/60, which means that even if you find a single resonance, it doesn't get passed on to setup_notches.

**Comment by eyyoung24** [comment]
I'm having trouble reproducing the issue @swh76 

`In [17]: S.setup_notches(2, new_master_assignment=True)
[ 2019-12-17 01:12:00 ]  No drive given. Using value in config file: 12
[ 2019-12-17 01:12:00 ]  Assigning channels
[ 2019-12-17 01:12:00 ]  No resonator frequencies provided. Not assigning
[ 2019-12-17 01:12:00 ]  Saving to : /data/smurf_data/tune/1576545120_tune.npy
[ 2019-12-17 01:12:00 ]  Relocking...
[ 2019-12-17 01:12:08 ]  Setting on 0 channels on band 2

In [18]: S.freq_resp[2]['resonances']
Out[18]: {}
`
