### ISSUE TITLE
UC & DC attenuator validation script

### ISSUE THREAD

**Issue by swh76** [slaclab/pysmurf#84]
I found an issue with the attenuators on the AMCs which Dan has fixed but we should confirm that the fix is working and reliable.  Need a script that can generate a matrix of DC and UC attenuator settings & full band response acquisitions to confirm the attenuators are functioning as expected.

**Comment by eyyoung24** [comment]
Solved in test scripts:
https://github.com/slaclab/pysmurf/blob/pre-release-test-scripts/python/pysmurf/client/test/test_loopback.py
